version: '3'
services:
  redis-node-0:
    build:
      context: ./redis_node
      dockerfile: ./Dockerfile
    container_name: redis-node-0
    volumes:
      - redis-cluster_data-0:/data

  redis-node-1:
    build:
      context: ./redis_node
      dockerfile: ./Dockerfile
    container_name: redis-node-1
    volumes:
      - redis-cluster_data-1:/data

  redis-node-2:
    build:
      context: ./redis_node
      dockerfile: ./Dockerfile
    container_name: redis-node-2
    volumes:
      - redis-cluster_data-2:/data

  redis-node-3:
    build:
      context: ./redis_node
      dockerfile: ./Dockerfile
    container_name: redis-node-3
    volumes:
      - redis-cluster_data-3:/data

  redis-node-4:
    build:
      context: ./redis_node
      dockerfile: ./Dockerfile
    container_name: redis-node-4
    volumes:
      - redis-cluster_data-4:/data

  redis-node-5:
    build:
      context: ./redis_node
      dockerfile: ./Dockerfile
    container_name: redis-node-5
    volumes:
      - redis-cluster_data-5:/data

  redis-cluster-init:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: redis-cluster-init
    depends_on:
      - redis-node-0
      - redis-node-1
      - redis-node-2
      - redis-node-3
      - redis-node-4
      - redis-node-5
    environment:
      - 'PORT=6379'
      - 'REDIS_CLUSTER_REPLICAS=1'
      - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5'

  redis-cluster-stats:
    image: insready/redis-stat
    container_name: redis_stat
    command: --server redis-node-0:6379 redis-node-1:6379 redis-node-2:6379 redis-node-3:6379 redis-node-4:6379 redis-node-5:6379
    ports:
      - "8080:63790"
    depends_on:
      - redis-node-0
      - redis-node-1
      - redis-node-2
      - redis-node-3
      - redis-node-4
      - redis-node-5
      - redis-cluster-init

volumes:
  redis-cluster_data-0:
    driver: local
  redis-cluster_data-1:
    driver: local
  redis-cluster_data-2:
    driver: local
  redis-cluster_data-3:
    driver: local
  redis-cluster_data-4:
    driver: local
  redis-cluster_data-5:
    driver: local
